# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('std_price', models.CharField(blank=True, default='', max_length=100)),
                ('price_buy', models.CharField(blank=True, default='', max_length=100)),
                ('price_sell', models.CharField(blank=True, default='', max_length=100)),
                ('price_send', models.CharField(blank=True, default='', max_length=100)),
                ('price_receive', models.CharField(blank=True, default='', max_length=100)),
                ('to_usd', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
